# Generated by Django 4.2.30 on 2026-06-04 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pcp.models
import pcp.storage
import uuid


def preencher_historico_execucoes(apps, schema_editor):
    Execucao = apps.get_model('pcp', 'PcpExecucaoManutencao')
    queryset = Execucao.objects.select_related('ativo_pcp__area', 'programacao__plano').using(
        schema_editor.connection.alias
    )
    for execucao in queryset.iterator():
        execucao.protocolo = uuid.uuid4()
        execucao.concluido_em = execucao.data_fim
        execucao.snapshot_ativo_codigo = execucao.ativo_pcp.codigo
        execucao.snapshot_ativo_nome = execucao.ativo_pcp.nome
        execucao.snapshot_ativo_numero_serie = execucao.ativo_pcp.numero_serie
        execucao.snapshot_area_nome = execucao.ativo_pcp.area.nome
        if execucao.programacao_id:
            execucao.snapshot_plano_nome = execucao.programacao.plano.nome
            execucao.snapshot_plano_tipo = execucao.programacao.plano.tipo
        execucao.save(
            update_fields=[
                'protocolo',
                'concluido_em',
                'snapshot_ativo_codigo',
                'snapshot_ativo_nome',
                'snapshot_ativo_numero_serie',
                'snapshot_area_nome',
                'snapshot_plano_nome',
                'snapshot_plano_tipo',
            ]
        )


def criar_eventos_historicos(apps, schema_editor):
    Execucao = apps.get_model('pcp', 'PcpExecucaoManutencao')
    Evento = apps.get_model('pcp', 'PcpEventoAuditoriaManutencao')
    alias = schema_editor.connection.alias
    eventos = []
    for execucao in Execucao.objects.using(alias).iterator():
        eventos.append(
            Evento(
                execucao_id=execucao.pk,
                tipo_evento='concluida' if execucao.data_fim else 'iniciada',
                justificativa='Registro historico incorporado na implantacao da auditoria.',
                dados={'migrado': True},
            )
        )
        if len(eventos) >= 500:
            Evento.objects.using(alias).bulk_create(eventos)
            eventos = []
    if eventos:
        Evento.objects.using(alias).bulk_create(eventos)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pcp', '0007_alter_pcpparametroalerta_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PcpEventoAuditoriaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('criada', 'Manutencao criada'), ('iniciada', 'Manutencao iniciada'), ('concluida', 'Manutencao concluida'), ('corrigida', 'Correcao documental'), ('evidencia_adicionada', 'Evidencia adicionada'), ('evidencia_desativada', 'Evidencia desativada')], db_index=True, max_length=40, verbose_name='Tipo de evento')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='Dados do evento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Evento de Auditoria de Manutencao',
                'verbose_name_plural': 'Eventos de Auditoria de Manutencao',
                'db_table': 'pcp_evento_auditoria_manutencao',
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.CreateModel(
            name='PcpEvidenciaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('arquivo', models.FileField(max_length=500, storage=pcp.storage.PcpPrivateStorage(), upload_to=pcp.models.evidencia_manutencao_upload_to, verbose_name='Arquivo')),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('imagem', 'Imagem')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome original')),
                ('tipo_mime', models.CharField(max_length=100, verbose_name='Tipo MIME')),
                ('tamanho_bytes', models.PositiveBigIntegerField(verbose_name='Tamanho em bytes')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Evidencia de Manutencao',
                'verbose_name_plural': 'Evidencias de Manutencao',
                'db_table': 'pcp_evidencia_manutencao',
                'permissions': [('desativar_evidencia_manutencao', 'Pode desativar evidencia de manutencao')],
            },
        ),
        migrations.CreateModel(
            name='PcpProgramacaoAlertaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('dias_antecedencia', models.PositiveSmallIntegerField(db_index=True, verbose_name='Dias de antecedencia')),
                ('data_disparo', models.DateField(db_index=True, verbose_name='Data programada para disparo')),
                ('destinatarios', models.TextField(verbose_name='Destinatarios')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviando', 'Enviando'), ('enviado', 'Enviado'), ('falha', 'Falha'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('tentativas', models.PositiveIntegerField(default=0, verbose_name='Tentativas')),
                ('ultimo_erro', models.TextField(blank=True, verbose_name='Ultimo erro')),
                ('enviado_em', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Enviado em')),
            ],
            options={
                'verbose_name': 'Programacao de Alerta de Manutencao',
                'verbose_name_plural': 'Programacoes de Alertas de Manutencao',
                'db_table': 'pcp_programacao_alerta_manutencao',
            },
        ),
        migrations.AlterModelOptions(
            name='pcpexecucaomanutencao',
            options={'permissions': [('corrigir_execucao_concluida', 'Pode corrigir execucao de manutencao concluida')], 'verbose_name': 'Execucao de Manutencao', 'verbose_name_plural': 'Execucoes de Manutencao'},
        ),
        migrations.AddField(
            model_name='pcpexecucaomanutencao',
            name='concluido_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Concluido em'),
        ),
        migrations.AddField(
            model_name='pcpexecucaomanutencao',
            name='concluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_manutencao_concluidas_pcp', to=settings.AUTH_USER_MODEL, verbose_name='Concluido por'),
        ),
        migrations.AddField(
            model_name='pcpexecucaomanutencao',
            name='diagnostico',
            field=models.TextField(blank=True, verbose_name='Diagnostico'),
        ),
        migrations.AddField(
            model_name='pcpexecucaomanutencao',
            name='protocolo',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='Protocolo'),
        ),
        migrations.AddField(
            model_name='pcpexecucaomanutencao',
            name='recomendacoes',
            field=models.TextField(blank=True, verbose_name='Recomendacoes'),
        ),
        migrations.AddField(
            model_name='pcpexecucaomanutencao',
            name='resultado',
            field=models.TextField(blank=True, verbose_name='Resultado'),
        ),
        migrations.AddField(
            model_name='pcpexecucaomanutencao',
            name='servicos_executados',
            field=models.TextField(blank=True, verbose_name='Servicos executados'),
        ),
        migrations.AddField(
            model_name='pcpexecucaomanutencao',
            name='snapshot_area_nome',
            field=models.CharField(blank=True, max_length=120, verbose_name='Area no fechamento'),
        ),
        migrations.AddField(
            model_name='pcpexecucaomanutencao',
            name='snapshot_ativo_codigo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Codigo do ativo no fechamento'),
        ),
        migrations.AddField(
            model_name='pcpexecucaomanutencao',
            name='snapshot_ativo_nome',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do ativo no fechamento'),
        ),
        migrations.AddField(
            model_name='pcpexecucaomanutencao',
            name='snapshot_ativo_numero_serie',
            field=models.CharField(blank=True, max_length=120, verbose_name='Numero de serie no fechamento'),
        ),
        migrations.AddField(
            model_name='pcpexecucaomanutencao',
            name='snapshot_plano_nome',
            field=models.CharField(blank=True, max_length=150, verbose_name='Plano no fechamento'),
        ),
        migrations.AddField(
            model_name='pcpexecucaomanutencao',
            name='snapshot_plano_tipo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo do plano no fechamento'),
        ),
        migrations.RunPython(preencher_historico_execucoes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pcpexecucaomanutencao',
            name='protocolo',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Protocolo'),
        ),
        migrations.AlterField(
            model_name='pcpalertaenviado',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviando', 'Enviando'), ('enviado', 'Enviado'), ('falha', 'Falha'), ('cancelado', 'Cancelado')], db_index=True, default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='pcpexecucaomanutencao',
            index=models.Index(fields=['concluido_em', 'ativo'], name='pcp_exec_concluido_idx'),
        ),
        migrations.AddField(
            model_name='pcpprogramacaoalertamanutencao',
            name='programacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programacoes_alerta', to='pcp.pcpprogramacaomanutencao', verbose_name='Programacao de manutencao'),
        ),
        migrations.AddField(
            model_name='pcpevidenciamanutencao',
            name='enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_manutencao_pcp', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AddField(
            model_name='pcpevidenciamanutencao',
            name='execucao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='pcp.pcpexecucaomanutencao', verbose_name='Execucao'),
        ),
        migrations.AddField(
            model_name='pcpeventoauditoriamanutencao',
            name='execucao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_auditoria', to='pcp.pcpexecucaomanutencao', verbose_name='Execucao'),
        ),
        migrations.AddField(
            model_name='pcpeventoauditoriamanutencao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria_manutencao_pcp', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.RunPython(criar_eventos_historicos, migrations.RunPython.noop),
        migrations.AddField(
            model_name='pcpalertaenviado',
            name='programacao_alerta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='pcp.pcpprogramacaoalertamanutencao', verbose_name='Programacao do alerta'),
        ),
        migrations.AddIndex(
            model_name='pcpprogramacaoalertamanutencao',
            index=models.Index(fields=['status', 'data_disparo'], name='pcp_prgalrt_status_data_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpprogramacaoalertamanutencao',
            index=models.Index(fields=['programacao', 'ativo'], name='pcp_prog_alerta_prog_ativo_idx'),
        ),
        migrations.AddConstraint(
            model_name='pcpprogramacaoalertamanutencao',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('programacao', 'dias_antecedencia', 'destinatarios'), name='pcp_prog_alerta_marco_dest_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pcpprogramacaoalertamanutencao',
            constraint=models.CheckConstraint(check=models.Q(('dias_antecedencia__in', (30, 15, 7, 1))), name='pcp_prog_alerta_marco_valido'),
        ),
        migrations.AddIndex(
            model_name='pcpevidenciamanutencao',
            index=models.Index(fields=['execucao', 'ativo'], name='pcp_evid_exec_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpevidenciamanutencao',
            index=models.Index(fields=['tipo', 'ativo'], name='pcp_evid_tipo_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpeventoauditoriamanutencao',
            index=models.Index(fields=['execucao', 'criado_em'], name='pcp_audit_exec_criado_idx'),
        ),
        migrations.AddIndex(
            model_name='pcpeventoauditoriamanutencao',
            index=models.Index(fields=['tipo_evento', 'criado_em'], name='pcp_audit_tipo_criado_idx'),
        ),
    ]
