# Generated by Django 4.2.30 on 2026-06-04 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pcp', '0008_pcpeventoauditoriamanutencao_pcpevidenciamanutencao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacaoestoquepcp',
            options={'verbose_name': 'Movimentação de Estoque (PCP)', 'verbose_name_plural': 'Movimentações de Estoque (PCP)'},
        ),
        migrations.AlterModelOptions(
            name='pcpareaproducao',
            options={'verbose_name': 'Área de Produção', 'verbose_name_plural': 'Áreas de Produção'},
        ),
        migrations.AlterModelOptions(
            name='pcpeventoauditoriamanutencao',
            options={'default_permissions': ('add', 'view'), 'verbose_name': 'Evento de Auditoria de Manutenção', 'verbose_name_plural': 'Eventos de Auditoria de Manutenção'},
        ),
        migrations.AlterModelOptions(
            name='pcpevidenciamanutencao',
            options={'permissions': [('desativar_evidencia_manutencao', 'Pode desativar evidência de manutenção')], 'verbose_name': 'Evidência de Manutenção', 'verbose_name_plural': 'Evidências de Manutenção'},
        ),
        migrations.AlterModelOptions(
            name='pcpexecucaomanutencao',
            options={'permissions': [('corrigir_execucao_concluida', 'Pode corrigir execução de manutenção concluída')], 'verbose_name': 'Execução de Manutenção', 'verbose_name_plural': 'Execuções de Manutenção'},
        ),
        migrations.AlterModelOptions(
            name='pcpparametroalerta',
            options={'verbose_name': 'Parâmetro de Alerta PCP', 'verbose_name_plural': 'Parâmetros de Alerta PCP'},
        ),
        migrations.AlterModelOptions(
            name='pcpplanomanutencao',
            options={'verbose_name': 'Plano de Manutenção', 'verbose_name_plural': 'Planos de Manutenção'},
        ),
        migrations.AlterModelOptions(
            name='pcpprogramacaoalertamanutencao',
            options={'verbose_name': 'Programação de Alerta de Manutenção', 'verbose_name_plural': 'Programações de Alertas de Manutenção'},
        ),
        migrations.AlterModelOptions(
            name='pcpprogramacaomanutencao',
            options={'verbose_name': 'Programação de Manutenção', 'verbose_name_plural': 'Programações de Manutenção'},
        ),
        migrations.AlterField(
            model_name='movimentacaoestoquepcp',
            name='cf_operacao',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='CF da Operação (SD3)'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoquepcp',
            name='data_movimentacao',
            field=models.DateField(db_index=True, verbose_name='Data da Movimentação'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoquepcp',
            name='origem_movimentacao',
            field=models.CharField(choices=[('NF_ENTRADA', 'Nota Fiscal de Entrada'), ('NF_SAIDA', 'Nota Fiscal de Saída'), ('MOV_INTERNA', 'Movimentação Interna')], db_index=True, max_length=20, verbose_name='Origem da Movimentação'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoquepcp',
            name='produto_codigo',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Código do Produto'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoquepcp',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], db_index=True, max_length=10, verbose_name='Tipo de Movimentação'),
        ),
        migrations.AlterField(
            model_name='pcpalertaenviado',
            name='chave_idempotencia',
            field=models.CharField(db_index=True, max_length=120, unique=True, verbose_name='Chave de idempotência'),
        ),
        migrations.AlterField(
            model_name='pcpalertaenviado',
            name='data_referencia',
            field=models.DateField(db_index=True, verbose_name='Data de referência'),
        ),
        migrations.AlterField(
            model_name='pcpalertaenviado',
            name='destinatarios',
            field=models.TextField(verbose_name='Destinatários'),
        ),
        migrations.AlterField(
            model_name='pcpalertaenviado',
            name='parametro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_enviados', to='pcp.pcpparametroalerta', verbose_name='Parâmetro'),
        ),
        migrations.AlterField(
            model_name='pcpalertaenviado',
            name='programacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_enviados', to='pcp.pcpprogramacaomanutencao', verbose_name='Programação'),
        ),
        migrations.AlterField(
            model_name='pcpalertaenviado',
            name='programacao_alerta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='pcp.pcpprogramacaoalertamanutencao', verbose_name='Programação do alerta'),
        ),
        migrations.AlterField(
            model_name='pcpalertaenviado',
            name='ultimo_erro',
            field=models.TextField(blank=True, verbose_name='Último erro'),
        ),
        migrations.AlterField(
            model_name='pcpareaproducao',
            name='codigo',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='pcpareaproducao',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='pcpativo',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ativos', to='pcp.pcpareaproducao', verbose_name='Área de Produção'),
        ),
        migrations.AlterField(
            model_name='pcpativo',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='pcpativo',
            name='criticidade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], db_index=True, default='media', max_length=20, verbose_name='Criticidade'),
        ),
        migrations.AlterField(
            model_name='pcpativo',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='pcpativo',
            name='numero_serie',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='pcpativo',
            name='status',
            field=models.CharField(choices=[('operando', 'Operando'), ('parado', 'Parado'), ('manutencao', 'Em manutenção'), ('inativo', 'Inativo')], db_index=True, default='operando', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pcpdowntime',
            name='duracao_minutos',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Duração em minutos'),
        ),
        migrations.AlterField(
            model_name='pcpdowntime',
            name='inicio',
            field=models.DateTimeField(db_index=True, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='pcpdowntime',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='pcpdowntime',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtimes_pcp', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='pcpdowntime',
            name='tipo',
            field=models.CharField(choices=[('nao_planejado', 'Não planejado'), ('planejado', 'Planejado'), ('setup', 'Setup'), ('qualidade', 'Qualidade'), ('falta_material', 'Falta de material'), ('manutencao', 'Manutenção')], db_index=True, max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='pcpeventoauditoriamanutencao',
            name='execucao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_auditoria', to='pcp.pcpexecucaomanutencao', verbose_name='Execução'),
        ),
        migrations.AlterField(
            model_name='pcpeventoauditoriamanutencao',
            name='tipo_evento',
            field=models.CharField(choices=[('criada', 'Manutenção criada'), ('iniciada', 'Manutenção iniciada'), ('concluida', 'Manutenção concluída'), ('corrigida', 'Correção documental'), ('evidencia_adicionada', 'Evidência adicionada'), ('evidencia_desativada', 'Evidência desativada')], db_index=True, max_length=40, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='pcpeventoauditoriamanutencao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria_manutencao_pcp', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='pcpevidenciamanutencao',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='pcpevidenciamanutencao',
            name='execucao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to='pcp.pcpexecucaomanutencao', verbose_name='Execução'),
        ),
        migrations.AlterField(
            model_name='pcpexecucaomanutencao',
            name='concluido_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Concluído em'),
        ),
        migrations.AlterField(
            model_name='pcpexecucaomanutencao',
            name='concluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_manutencao_concluidas_pcp', to=settings.AUTH_USER_MODEL, verbose_name='Concluído por'),
        ),
        migrations.AlterField(
            model_name='pcpexecucaomanutencao',
            name='data_inicio',
            field=models.DateTimeField(db_index=True, verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='pcpexecucaomanutencao',
            name='diagnostico',
            field=models.TextField(blank=True, verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='pcpexecucaomanutencao',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='pcpexecucaomanutencao',
            name='programacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes', to='pcp.pcpprogramacaomanutencao', verbose_name='Programação'),
        ),
        migrations.AlterField(
            model_name='pcpexecucaomanutencao',
            name='recomendacoes',
            field=models.TextField(blank=True, verbose_name='Recomendações'),
        ),
        migrations.AlterField(
            model_name='pcpexecucaomanutencao',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_manutencao_pcp', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='pcpexecucaomanutencao',
            name='servicos_executados',
            field=models.TextField(blank=True, verbose_name='Serviços executados'),
        ),
        migrations.AlterField(
            model_name='pcpexecucaomanutencao',
            name='snapshot_area_nome',
            field=models.CharField(blank=True, max_length=120, verbose_name='Área no fechamento'),
        ),
        migrations.AlterField(
            model_name='pcpexecucaomanutencao',
            name='snapshot_ativo_codigo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código do ativo no fechamento'),
        ),
        migrations.AlterField(
            model_name='pcpexecucaomanutencao',
            name='snapshot_ativo_numero_serie',
            field=models.CharField(blank=True, max_length=120, verbose_name='Número de série no fechamento'),
        ),
        migrations.AlterField(
            model_name='pcpexecucaomanutencao',
            name='tipo',
            field=models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('preditiva', 'Preditiva'), ('inspecao', 'Inspeção')], db_index=True, max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='pcpparametroalerta',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parametros_alerta', to='pcp.pcpareaproducao', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='pcpparametroalerta',
            name='dias_antecedencia',
            field=models.PositiveIntegerField(default=7, verbose_name='Dias de antecedência'),
        ),
        migrations.AlterField(
            model_name='pcpparametroalerta',
            name='emails_destino',
            field=models.TextField(verbose_name='E-mails de destino'),
        ),
        migrations.AlterField(
            model_name='pcpplanomanutencao',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='pcpplanomanutencao',
            name='tipo',
            field=models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('preditiva', 'Preditiva'), ('inspecao', 'Inspeção')], db_index=True, default='preventiva', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='pcpprogramacaoalertamanutencao',
            name='destinatarios',
            field=models.TextField(verbose_name='Destinatários'),
        ),
        migrations.AlterField(
            model_name='pcpprogramacaoalertamanutencao',
            name='dias_antecedencia',
            field=models.PositiveSmallIntegerField(db_index=True, verbose_name='Dias de antecedência'),
        ),
        migrations.AlterField(
            model_name='pcpprogramacaoalertamanutencao',
            name='programacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programacoes_alerta', to='pcp.pcpprogramacaomanutencao', verbose_name='Programação de manutenção'),
        ),
        migrations.AlterField(
            model_name='pcpprogramacaoalertamanutencao',
            name='ultimo_erro',
            field=models.TextField(blank=True, verbose_name='Último erro'),
        ),
        migrations.AlterField(
            model_name='pcpprogramacaomanutencao',
            name='status',
            field=models.CharField(choices=[('planejada', 'Planejada'), ('em_execucao', 'Em execução'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], db_index=True, default='planejada', max_length=20, verbose_name='Status'),
        ),
    ]
