# Generated by Django 4.2.30 on 2026-06-16 16:56

from django.db import migrations, models
from django.utils import timezone
import django.db.models.deletion
from datetime import timedelta


def preencher_status_e_expiracao_pesquisas(apps, schema_editor):
    PesquisaDemissional = apps.get_model('rh', 'PesquisaDemissional')
    agora = timezone.now()

    for pesquisa in PesquisaDemissional.objects.all():
        data_base = pesquisa.data_geracao or agora
        data_expiracao = pesquisa.data_expiracao or data_base + timedelta(days=15)

        if pesquisa.respondida or pesquisa.data_resposta or pesquisa.nota_lideranca is not None:
            status = 'RESPONDIDA'
        elif data_expiracao < agora:
            status = 'EXPIRADA'
        else:
            status = 'PENDENTE'

        PesquisaDemissional.objects.filter(pk=pesquisa.pk).update(
            data_expiracao=data_expiracao,
            status=status,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0020_avaliacao_usuario_snapshot_ciencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisademissional',
            name='data_expiracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesquisademissional',
            name='pesquisa_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novos_links', to='rh.pesquisademissional'),
        ),
        migrations.AddField(
            model_name='pesquisademissional',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('RESPONDIDA', 'Respondida'), ('EXPIRADA', 'Expirada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20),
        ),
        migrations.RunPython(preencher_status_e_expiracao_pesquisas, migrations.RunPython.noop),
        migrations.AddField(
            model_name='solicitacaovaga',
            name='banco_de_talentos',
            field=models.BooleanField(default=False, verbose_name='Banco de Talentos'),
        ),
        migrations.AlterField(
            model_name='pesquisademissional',
            name='tipo_demissao',
            field=models.CharField(choices=[('VOLUNTARIA', 'Pedido de Demissão (Iniciativa do Colaborador)'), ('INVOLUNTARIA', 'Demissão sem Justa Causa (Iniciativa da Empresa)'), ('JUSTA_CAUSA', 'Demissão por Justa Causa'), ('ACORDO', 'Acordo entre as partes'), ('TERMINO_CONTRATO_TRABALHO', 'Termino de Contrato de Trabalho')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitacaovaga',
            name='data_prevista_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data Prevista para Início'),
        ),
    ]
