# Generated by Django 4.2.30 on 2026-06-18 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from datetime import date


def preencher_ciclos_e_bloqueio(apps, schema_editor):
    AvaliacaoDesempenho = apps.get_model('rh', 'AvaliacaoDesempenho')
    CicloAvaliacaoDesempenho = apps.get_model('rh', 'CicloAvaliacaoDesempenho')

    for avaliacao in AvaliacaoDesempenho.objects.all():
        if avaliacao.ciclo == 'A':
            data_inicio = date(int(avaliacao.ano), 1, 1)
            data_fim = date(int(avaliacao.ano), 6, 30)
        else:
            data_inicio = date(int(avaliacao.ano), 7, 1)
            data_fim = date(int(avaliacao.ano), 12, 31)

        ciclo, _ = CicloAvaliacaoDesempenho.objects.get_or_create(
            ano=avaliacao.ano,
            ciclo=avaliacao.ciclo,
            defaults={
                'data_inicio': data_inicio,
                'data_fim': data_fim,
                'ativo': True,
            },
        )
        avaliacao.ciclo_avaliacao_id = ciclo.pk
        avaliacao.bloqueada = bool(avaliacao.ciencia_gestor and avaliacao.ciencia_colaborador)
        avaliacao.save(update_fields=['ciclo_avaliacao', 'bloqueada'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rh', '0021_pesquisademissional_data_expiracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaodesempenho',
            name='bloqueada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='centro_custo_planilha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='departamento_planilha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='gestor_nome_planilha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='servico_planilha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='usuario_planilha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='VinculoAvaliacaoDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestor_nome_planilha', models.CharField(blank=True, max_length=255, null=True)),
                ('gestor_email_resolvido', models.EmailField(blank=True, max_length=254, null=True)),
                ('setor_avaliado', models.CharField(blank=True, max_length=10, null=True)),
                ('setor_gestor', models.CharField(blank=True, max_length=10, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('origem', models.CharField(default='PLANILHA', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_avaliacao', to='rh.funcionario')),
                ('gestor_funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliados_como_gestor', to='rh.funcionario')),
                ('gestor_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliados_vinculados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vinculo de avaliacao de desempenho',
                'verbose_name_plural': 'Vinculos de avaliacao de desempenho',
                'ordering': ['avaliado__nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='CicloAvaliacaoDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('ciclo', models.CharField(choices=[('A', 'Ciclo A - Janeiro a Junho'), ('B', 'Ciclo B - Julho a Dezembro')], max_length=1)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ciclo de avaliacao de desempenho',
                'verbose_name_plural': 'Ciclos de avaliacao de desempenho',
                'ordering': ['-ano', '-ciclo'],
                'unique_together': {('ano', 'ciclo')},
            },
        ),
        migrations.AddField(
            model_name='avaliacaodesempenho',
            name='ciclo_avaliacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes', to='rh.cicloavaliacaodesempenho'),
        ),
        migrations.RunPython(preencher_ciclos_e_bloqueio, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='vinculoavaliacaodesempenho',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('avaliado',), name='rh_vinculo_avaliacao_ativo_avaliado_uniq'),
        ),
    ]
