# Generated by Django 6.0.2 on 2026-03-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_is_compras_customuser_is_pcp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_qualidade',
            field=models.BooleanField(default=False, verbose_name='Acesso Qualidade'),
        ),
    ]
