# Generated by Django 6.0.2 on 2026-03-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='categoria',
            field=models.CharField(choices=[('HARDWARE', 'Hardware (computadores, notebooks, impressoras, periféricos)'), ('SOFTWARE_BASICO', 'Software Básico (sistema operacional, drivers, office)'), ('SOFTWARE_CORPORATIVO', 'Sistemas Corporativos (ERP, PROTHEUS, CRM, BI)'), ('REDE', 'Rede e Conectividade (internet, VPN, switches, roteadores)'), ('ACESSO', 'Gestão de Acessos (criação/remoção de usuários, senhas, permissões)'), ('SEGURANCA', 'Segurança da Informação (antivírus, firewall, incidentes, backup)'), ('INFRAESTRUTURA', 'Infraestrutura (servidores, storage, virtualização, backups)'), ('BANCO_DADOS', 'Banco de Dados (manutenção, performance, consultas)'), ('TELEFONIA', 'Telefonia / VoIP (ramais, softphones, centrais)'), ('EMAIL', 'Correio Eletrônico e Colaboração (e-mail, calendário, Teams, Slack)'), ('DESENVOLVIMENTO', 'Desenvolvimento (criação de apps, sites, sistemas, automações)'), ('MOBILIDADE', 'Dispositivos Móveis (celulares, tablets, configuração de e-mail)'), ('NUVEM', 'Serviços em Nuvem (AWS, Azure, Google Workspace, Dropbox)'), ('IMPRESSAO', 'Impressão e Digitalização (configuração, manutenção, filas)'), ('TREINAMENTO', 'Treinamento e Orientação (uso de sistemas, boas práticas)'), ('OUTROS', 'Outros (demandas não classificadas nas categorias anteriores)')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa - Impacto mínimo, sem interrupção'), ('MEDIA', 'Média - Impacto localizado, mas não impede o trabalho'), ('ALTA', 'Alta - Setor ou processo parcialmente interrompido'), ('CRITICA', 'Crítica - Operação da empresa interrompida (atendimento imediato)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='setor',
            field=models.CharField(choices=[('COMERCIAL', 'Comercial'), ('COMPRAS', 'Compras'), ('DIRETORIA', 'Diretoria'), ('FINANCEIRO', 'Financeiro'), ('OBRA', 'Obra'), ('ORCAMENTO', 'Orçamento'), ('PLANETAMENTO PROCESSO E QUALIDADE', 'Planejamento Processo e Qualidade'), ('PRODUCAO', 'Produção'), ('PROJETOS', 'Projetos'), ('RECURSOS HUMADOS', 'Recursos Humados'), ('T.I', 'T.I')], default='', max_length=50),
        ),
    ]
