# Generated by Django 4.2.30 on 2026-05-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estruturaproduto',
            name='codigo_componente',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Código Componente'),
        ),
        migrations.AlterField(
            model_name='estruturaproduto',
            name='codigo_pai',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Código Pai'),
        ),
        migrations.AlterField(
            model_name='estruturaproduto',
            name='data_importacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Importação'),
        ),
        migrations.AlterField(
            model_name='estruturaproduto',
            name='fim_validade',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fim Validade'),
        ),
        migrations.AlterField(
            model_name='estruturaproduto',
            name='inicio_validade',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Ini. Validade'),
        ),
        migrations.AlterField(
            model_name='estruturaproduto',
            name='tipo_pai',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='Tipo Pai'),
        ),
    ]
